---
  version: "2.1"
  services:
    jenkins:
      # https://hub.docker.com/r/jenkins/jenkins/
      image: jenkins/jenkins:lts
      container_name: jenkins
      user: ${PUID}
      volumes:
        - ${PATH_CONFIG}/jenkins:/var/jenkins_home
      ports:
        - 8081:8080
        - 50000:50000
      restart: unless-stopped